---
baseurl: /
blackfriday:
  extensionsmask: ["noIntraEmphasis"]
  fractions: false
disqusShortname: Shouyue Liu
footnotereturnlinkcontents: 
googleAnalytics: ''
hasCJKLanguage: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  about:
    - name: Home/主页
      url: /
      weight: 1
    - name: Blog/博客
      url: /blog/
      weight: 2
    - name: About/关于我
      url: /about/
      weight: 5
  blog:
    - name: Home/主页
      url: /
      weight: 1
    - name: Blog/博客
      url: /blog/
      weight: 2
    - name: About/关于我
      url: /about/
      weight: 5
  main:
    - name: Home/主页
      url: /
      weight: 1
    - name: Blog/博客
      url: /blog/
      weight: 2
    - name: About/关于我
      url: /about/
      weight: 5
params:
  author:
    cn: Shouyue Liu
    en: Shouyue Liu
  customJS:
    - js/fix-toc.js
    - js/center-img.js
    - js/right-quote.js
    - js/no-highlight.js
    - js/fix-footnote.js
    - js/math-code.js
    - js/external-link.js
    - js/alt-title.js
    - js/header-link.js
  description: 我們今天所叫做生活的，過後它便是歷史。
  footer: '&copy; [Shouyue Liu](https://iaaronlau.github.io/) 2023 | [Github](https://github.com/iaaronlau) | [Subscribe](https://iaaronlau.github.io/index.xml) | [Jinji](https://jinjipang.com)'
  highlightjsCDN: //cdn.bootcss.com
  highlightjsLang: ["r", "yaml", "tex", "shell", "python"]
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/
preserveTaxonomyNames: true
rssLimit: 130
theme: hugo-ivy
title: Shouyue Liu